### PR TITLE
add extra secret tests from pynitrokey

### PR DESCRIPTION
**Pull request by blu-nitro**
Adds secrets tests from `pynitrokey`.
This is an effort to unify the test suites in order to make things easier for projects like hil.

**Changes**:
- All existing tests moved to `tests/default/`
- Default test directory changed to `test/default/`
- Extra tests reside in `tests/extra/`
- Added extra secrets tests from pynitrokey and everything required to execute them
- Added make target to execute the extra secrets tests

This should not change anything to current test execution via pytest, only that going forward tests that are supposed to be run by default will have to be placed in `tests/default/` instead of `tests/`.

It does however seem to generate a bunch of warnings, which i'm not sure whether they come from `pynitrokey` or from anything new.

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
Makes sense.  Why the distinction between `default` and `extra` tests?  Couldn’t we just put the new tests into `test/secrets.py`?

**Comment by blu-nitro** [comment]
If we were to just put the new tests into `test/secrets.py`, then with the current way we select tests with patterns, like `test_list or test_lsusb`, this would for example select `test_list_with_properties` as well from the new secrets tests. So we could rename some of them, but i didn't want to touch the tests themselves, as that was out scope for what i wanted to do with this PR.
But if you want, we could of course find another way of getting this to work with all tests in the same directory.

**Comment by robin-nitrokey** [comment]
I see.  We could introduce an `extra` marker and [apply](https://docs.pytest.org/en/7.1.x/example/markers.html#marking-whole-classes-or-modules) it to all tests in the module to be able to filter them.

**Review by robin-nitrokey — APPROVED** [review]
LGTM.  We should also document how fuzzing works, but that can be done in a separate PR.

**Comment by robin-nitrokey** [comment]
@blu-nitro This means we can now delete [`test_secrets_app.py`](https://github.com/Nitrokey/pynitrokey/blob/a5abc29d6eec9bbec73412fbb02a156143645c6d/pynitrokey/test_secrets_app.py) from pynitrokey, right?

**Comment by blu-nitro** [comment]
> @blu-nitro This means we can now delete [`test_secrets_app.py`](https://github.com/Nitrokey/pynitrokey/blob/a5abc29d6eec9bbec73412fbb02a156143645c6d/pynitrokey/test_secrets_app.py) from pynitrokey, right?

It is not needed in `nitrokey-hardware-test` anymore. I'm not sure if it was used anywhere else though.

**Pull request merged**
